const textdata = {
    "data": [
      "Success is not about the destination, but rather the journey and lessons learned along the way.",
      "The greatest challenge in life is discovering who you are, the second greatest is being happy with it.",
      "Sometimes the smallest decisions can change your life forever, so choose your path wisely and deliberately.",
      "Every obstacle you face is just another opportunity to prove how badly you want something.",
      "Your attitude towards challenges determines your altitude in life, so keep pushing forward with determination.",
      "Knowledge may give you power, but character earns you respect in the eyes of others.",
      "The difference between ordinary and extraordinary is that little extra effort you put in daily.",
      "Time is the most valuable currency we have, spend it wisely on things that truly matter.",
      "Real growth happens when you step outside your comfort zone and embrace new challenges ahead.",
      "The best way to predict your future is to create it through consistent actions today.",
      "Your potential is limited only by the boundaries you create in your own mind.",
      "Every expert was once a beginner who refused to give up on their dreams.",
      "Success comes to those who work smart and persevere through the toughest of challenges.",
      "The quality of your thoughts determines the quality of your life and future outcomes.",
      "Learning from mistakes is important, but learning from others' mistakes is pure wisdom indeed.",
      "Happiness is found when you stop comparing yourself to other people around you.",
      "Never let fear of failure prevent you from pursuing what could be your greatest achievement.",
      "Today's preparation determines tomorrow's achievement, so plan your steps carefully and thoughtfully.",
      "The harder you work for something, the greater you'll feel when you finally achieve it.",
      "Your future depends on what you do today, not tomorrow or the day after.",
      "Life becomes easier when you learn to accept the apology you never received from others.",
      "Great things never came from comfort zones, so push yourself beyond familiar boundaries.",
      "The only person you should try to compete with is the person you were yesterday.",
      "Being kind to others is free, yet it's the most valuable gift you can give.",
      "Sometimes the right path is not the easiest one, but it's worth taking anyway.",
      "Your actions speak louder than your words, so let your behavior reflect your intentions.",
      "The best revenge is massive success achieved through dedication and persistent hard work.",
      "Opportunities multiply as they are seized, so take action when chances present themselves.",
      "Focus on progress rather than perfection, and you'll find yourself moving forward consistently.",
      "The only limitations in life are the ones we make in our minds first.",
      "True wisdom comes from experience, and experience comes from making mistakes along the way.",
      "Every accomplishment starts with the decision to try something new and challenging.",
      "Innovation comes from questioning assumptions and thinking differently about common problems.",
      "The best leaders are those who know how to serve others before serving themselves.",
      "Success is built on daily habits that seem insignificant at the time but compound over time.",
      "Change is inevitable, growth is optional, choose wisely which path you'll take today.",
      "Small daily improvements are the key to long-term outstanding results in life.",
      "Your perspective on life comes from the cage you were held captive in.",
      "The only way to do great work is to love what you do completely.",
      "Dreams don't work unless you take action and put in the necessary effort.",
      "Life is short, break the rules, forgive quickly, love truly, laugh uncontrollably.",
      "The biggest risk is not taking any risk in a world that's changing quickly.",
      "What lies behind us and before us are tiny matters compared to what lies within.",
      "Don't watch the clock; do what it does and keep going forward consistently.",
      "Everything you've ever wanted is sitting on the other side of fear.",
      "The past cannot be changed, but the future is still in your power.",
      "Success usually comes to those who are too busy to be looking for it.",
      "Life begins at the end of your comfort zone, so embrace new challenges.",
      "Make each day count by focusing on what truly matters in your life.",
      "Believe you can and you're halfway there to achieving your dreams."
    ]
}
export default textdata